export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const OPEN_USER_INFO = 'OPEN_USER_INFO';
export const CLOSE_USER_INFO = 'CLOSE_USER_INFO';
export const OPEN_USER_INFO_MODAL = 'OPEN_USER_INFO_MODAL';
export const CLOSE_USER_INFO_MODAL = 'CLOSE_USER_INFO_MODAL';